export const GET_ALL_TILES_REQUEST = "GET_ALL_TILES_REQUEST";
export const GET_ALL_TILES_COMPLETED = "GET_ALL_TILES_COMPLETED";
export const GET_ALL_TILES_FAILED = "GET_ALL_TILES_FAILED";

export const GET_TILE_REQUEST = "GET_TILE_REQUEST";
export const GET_TILE_COMPLETED = "GET_TILE_COMPLETED";
export const GET_TILE_FAILED = "GET_TILE_FAILED";
